zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "49181:2181"
    - "22"
nimbus:
  image: wurstmeister/storm-nimbus
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links: 
    - zookeeper:zk
supervisor:
  image: wurstmeister/storm-supervisor
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: wurstmeister/storm-ui
  ports:
    - "49080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk

# Added by pgbsk, this is a variation from the base wurstmeister image
kafka:
  build: kafka
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
